# Generated by Django 5.2.8 on 2026-07-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_address',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_contact',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_nic',
            field=models.CharField(default='000000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('', 'Select Time Slot'), ('09:00-10:00', '09:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('11:00-12:00', '11:00 AM - 12:00 PM'), ('12:00-13:00', '12:00 PM - 01:00 PM'), ('13:00-14:00', '01:00 PM - 02:00 PM'), ('14:00-15:00', '02:00 PM - 03:00 PM'), ('15:00-16:00', '03:00 PM - 04:00 PM'), ('16:00-17:00', '04:00 PM - 05:00 PM')], default='09:00-10:00', max_length=20),
            preserve_default=False,
        ),
    ]
