# Generated by Django 5.2.8 on 2026-07-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_departmentfee_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='doctor_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
