# Generated by Django 5.2.8 on 2026-08-22 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_payment_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('', 'Select Time Slot'), ('09:00-10:00', '09:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('11:00-12:00', '11:00 AM - 12:00 PM'), ('12:00-13:00', '12:00 PM - 01:00 PM'), ('13:00-14:00', '01:00 PM - 02:00 PM'), ('14:00-15:00', '02:00 PM - 03:00 PM'), ('15:00-16:00', '03:00 PM - 04:00 PM'), ('16:00-17:00', '04:00 PM - 05:00 PM')], max_length=20)),
                ('doctor', models.ForeignKey(limit_choices_to={'profile__role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availability',
                'db_table': 'doctor_availability',
                'unique_together': {('doctor', 'time_slot')},
            },
        ),
    ]
