# Generated by Django 6.0.6 on 2026-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subjects', models.CharField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='active', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
