# Generated by Django 6.0.6 on 2026-08-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='subjects',
            new_name='subject',
        ),
    ]
