# Generated by Django 6.0.6 on 2026-08-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_us_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact_us',
            table='contact_messages',
        ),
    ]
