# Generated by Django 6.0.6 on 2026-08-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_us_id'),
        ('contact', '0004_alter_contact_us_id_alter_contact_us_table'),
    ]

    operations = [
    ]
