# Generated by Django 5.2.8 on 2026-08-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_seed_contact_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=20),
        ),
    ]
