# Generated by Django 5.2.8 on 2026-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contact_us_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
