# Generated by Django 6.0.6 on 2026-08-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='medicines',
        ),
        migrations.AlterModelTable(
            name='medicinestock',
            table='medicine_stocks',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='suppliers',
        ),
    ]
