# Generated by Django 5.2.8 on 2026-07-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_staffprofile_room_number_alter_patientprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='hourly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
