# Generated by Django 6.0.6 on 2026-08-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_staffprofile_drop_user_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientprofile',
            table='patient_profiles',
        ),
        migrations.AlterModelTable(
            name='staffprofile',
            table='staff_profiles',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
