# Generated by Django 5.2.8 on 2026-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_fix_doctor_consultation_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
