# Generated by Django 5.2.8 on 2026-08-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_alter_patientprofile_id_alter_staffprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='sector',
            field=models.CharField(blank=True, choices=[('', '---------'), ('government', 'Government'), ('private', 'Private')], max_length=20),
        ),
    ]
