# Generated by Django 5.2.8 on 2026-08-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_staffprofile_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='shift',
        ),
    ]
