# Generated by Django 5.2.8 on 2026-08-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_remove_staffprofile_hire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='sector',
        ),
    ]
